config/routes.rb
TestTask::Application.routes.draw do
  resources :secret_codes

  devise_for :users

  

   root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
     user ||= User.new # guest user (not logged in)
     if user.role? 
       can :manage, :all
     else
       can :read, :all
     end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
  attr_accessible :user_id, :code
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name,:secret_code,:role
  #validates :secret_code ,:inclusion => { :in => "foobar" }
  # attr_accessible :title, :body
  has_one :source_code, :class_name =>'SecretCode', :foreign_key => 'user_id'
  after_create :create_secret_code
  def create_secret_code
   source_code=SecretCode.find_by_id(secret_code)
   if source_code
     source_code.user_id =self.id
     source_code.save
   end
 end 

  def role?
    return true if self.role == 'admin'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  load_and_authorize_resource
  # GET /secret_codes
  # GET /secret_codes.json
  def index
    @secret_codes = SecretCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @secret_codes }
    end
  end

  # GET /secret_codes/1
  # GET /secret_codes/1.json
  def show
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/new
  # GET /secret_codes/new.json
  def new
    @secret_code = SecretCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/1/edit
  def edit
    @secret_code = SecretCode.find(params[:id])
  end

  # POST /secret_codes
  # POST /secret_codes.json
  def create
    h = params[:secret_code][:code].to_i
    h.times do 
    secret_code=(0...8).map{(65+rand(26)).chr}.join  
    @secret_code = SecretCode.create(:code=>secret_code.to_s)
    end
    respond_to do |format|
      if @secret_code.save
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully created.' }
        format.json { render json: @secret_code, status: :created, location: @secret_code }
      else
        format.html { render action: "new" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /secret_codes/1
  # PUT /secret_codes/1.json
  def update
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      if @secret_code.update_attributes(params[:secret_code])
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secret_codes/1
  # DELETE /secret_codes/1.json
  def destroy
    @secret_code = SecretCode.find(params[:id])
    @secret_code.destroy

    respond_to do |format|
      format.html { redirect_to secret_codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_of_code
    SecretCode.find(:all,:conditions => ["user_id is null"])
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
  def code
    [  ['1', 1],
       ['10', 10],
       ['20', 20],
       [' 30', 30],
       ['50',50] ,
       ['100', 100]
    ]
  end
end

app/views/home/index.html.erb
<%if current_user %>
<%= link_to "Signout", destroy_user_session_path, :method => :delete %>
<%else%>
<%= link_to "Signin", new_user_session_path %> or  <%= link_to "Signup", new_user_registration_path %> 
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/secret_codes/_form.html.erb
<%= form_for(@secret_code) do |f| %>
  <% if @secret_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secret_code.errors.count, "error") %> prohibited this secret_code from being saved:</h2>

      <ul>
      <% @secret_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%=f.label :code %><br />
    <%= f.select :code, code ,:selected =>['10',10] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secret_codes/edit.html.erb
<h1>Editing secret_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @secret_code %> |
<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/index.html.erb
<h3>Listing Secret Codes</h3>
<% if can? :create, SecretCode %>
<%= link_to  new_secret_code_path, :class => [:btn, :"btn-success"] do |l|%>
      <i class="icon-plus-sign icon-white"></i>
      New Secret code
    <% end %>
 <% end %>   
<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Email ID</th>
    <th>Secret Code</th>
    <th>Actions</th>
  </tr>
  </thead>
<% @secret_codes.each do |secret_code| %>
  <tr>
    <td><%= secret_code.user.try(:email)%></td>
    <td><%= secret_code.code%></td>
    <td><%= link_to 'Show', secret_code %></td>
    <% if can? :update, SecretCode %>
    <td><%= link_to 'Edit', edit_secret_code_path(secret_code) %></td>
    <% end %>
    <% if can? :update, SecretCode %>
    <td><%= link_to 'Destroy', secret_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/secret_codes/new.html.erb
<h1>New secret_code</h1>

<%= render 'form' %>

<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/show.html.erb
<h3> Secret Code <%=@secret_code.code%> Details </h3>
<div class="row">
<table class="table table-striped table-bordered">  
<tr>
 <td>User_id</td><td><%=@secret_code.user_id%> </td>
</tr>
<tr>
 <td>Code</td><td><%=@secret_code.code%> </td>
</tr>

 </table>
 </div>
<% if can? :update, @secret_code %> 
<%= link_to  edit_secret_code_path(@secret_code) , :class => [:btn, :"btn-success", :"btn-small"] do |l|%>
  <i class="icon-pencil icon-white"></i>
  Edit
<% end %>
<% end %>
<%= link_to 'Back', secret_codes_path %>